version: 0.1

phases:

  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - in28minutes-web-servlet-jsp/target/in28minutes.war
  discard-paths: yes